//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosPC4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentasLeonEntities : DbContext
    {
        public VentasLeonEntities()
            : base("name=VentasLeonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tb_Distrito> Tb_Distrito { get; set; }
        public DbSet<Tb_Orden_Compra> Tb_Orden_Compra { get; set; }
        public DbSet<Tb_Proveedor> Tb_Proveedor { get; set; }
    }
}
