//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosPC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Distrito
    {
        public Tb_Distrito()
        {
            this.Tb_Proveedor = new HashSet<Tb_Proveedor>();
        }
    
        public string Cod_dis { get; set; }
        public string Nom_dis { get; set; }
        public string Cod_ven { get; set; }
    
        public virtual ICollection<Tb_Proveedor> Tb_Proveedor { get; set; }
    }
}
