//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosPC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proveedor
    {
        public Tb_Proveedor()
        {
            this.Tb_Orden_Compra = new HashSet<Tb_Orden_Compra>();
        }
    
        public string Cod_prv { get; set; }
        public string Raz_soc_prv { get; set; }
        public string Dir_prv { get; set; }
        public string Tel_prv { get; set; }
        public string Cod_dis { get; set; }
        public string Rep_ven { get; set; }
    
        public virtual Tb_Distrito Tb_Distrito { get; set; }
        public virtual ICollection<Tb_Orden_Compra> Tb_Orden_Compra { get; set; }
    }
}
