//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.ProxyOrdenesCompra {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenesCompraBe", Namespace="http://schemas.datacontract.org/2004/07/ServiciosPC4")]
    [System.SerializableAttribute()]
    public partial class OrdenesCompraBe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstaOcoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecAteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaOcoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumOcoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonProvField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProv {
            get {
                return this.CodProvField;
            }
            set {
                if ((object.ReferenceEquals(this.CodProvField, value) != true)) {
                    this.CodProvField = value;
                    this.RaisePropertyChanged("CodProv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionProv {
            get {
                return this.DireccionProvField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionProvField, value) != true)) {
                    this.DireccionProvField = value;
                    this.RaisePropertyChanged("DireccionProv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrProv {
            get {
                return this.DistrProvField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrProvField, value) != true)) {
                    this.DistrProvField = value;
                    this.RaisePropertyChanged("DistrProv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstaOco {
            get {
                return this.EstaOcoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstaOcoField, value) != true)) {
                    this.EstaOcoField = value;
                    this.RaisePropertyChanged("EstaOco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecAte {
            get {
                return this.FecAteField;
            }
            set {
                if ((this.FecAteField.Equals(value) != true)) {
                    this.FecAteField = value;
                    this.RaisePropertyChanged("FecAte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaOco {
            get {
                return this.FechaOcoField;
            }
            set {
                if ((this.FechaOcoField.Equals(value) != true)) {
                    this.FechaOcoField = value;
                    this.RaisePropertyChanged("FechaOco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumOco {
            get {
                return this.NumOcoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumOcoField, value) != true)) {
                    this.NumOcoField = value;
                    this.RaisePropertyChanged("NumOco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonProv {
            get {
                return this.RazonProvField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonProvField, value) != true)) {
                    this.RazonProvField = value;
                    this.RaisePropertyChanged("RazonProv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyOrdenesCompra.IOrdenesCompra")]
    public interface IOrdenesCompra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesCompra/ListarOrdenes", ReplyAction="http://tempuri.org/IOrdenesCompra/ListarOrdenesResponse")]
        MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[] ListarOrdenes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesCompra/ListarOrdenes", ReplyAction="http://tempuri.org/IOrdenesCompra/ListarOrdenesResponse")]
        System.Threading.Tasks.Task<MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[]> ListarOrdenesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesCompra/ListarOrdenesProveedor", ReplyAction="http://tempuri.org/IOrdenesCompra/ListarOrdenesProveedorResponse")]
        MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[] ListarOrdenesProveedor(string CodPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesCompra/ListarOrdenesProveedor", ReplyAction="http://tempuri.org/IOrdenesCompra/ListarOrdenesProveedorResponse")]
        System.Threading.Tasks.Task<MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[]> ListarOrdenesProveedorAsync(string CodPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesCompra/ListarOrdenesEstado", ReplyAction="http://tempuri.org/IOrdenesCompra/ListarOrdenesEstadoResponse")]
        MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[] ListarOrdenesEstado(string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesCompra/ListarOrdenesEstado", ReplyAction="http://tempuri.org/IOrdenesCompra/ListarOrdenesEstadoResponse")]
        System.Threading.Tasks.Task<MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[]> ListarOrdenesEstadoAsync(string Estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenesCompraChannel : MvcApp.ProxyOrdenesCompra.IOrdenesCompra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenesCompraClient : System.ServiceModel.ClientBase<MvcApp.ProxyOrdenesCompra.IOrdenesCompra>, MvcApp.ProxyOrdenesCompra.IOrdenesCompra {
        
        public OrdenesCompraClient() {
        }
        
        public OrdenesCompraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenesCompraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenesCompraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenesCompraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[] ListarOrdenes() {
            return base.Channel.ListarOrdenes();
        }
        
        public System.Threading.Tasks.Task<MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[]> ListarOrdenesAsync() {
            return base.Channel.ListarOrdenesAsync();
        }
        
        public MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[] ListarOrdenesProveedor(string CodPro) {
            return base.Channel.ListarOrdenesProveedor(CodPro);
        }
        
        public System.Threading.Tasks.Task<MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[]> ListarOrdenesProveedorAsync(string CodPro) {
            return base.Channel.ListarOrdenesProveedorAsync(CodPro);
        }
        
        public MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[] ListarOrdenesEstado(string Estado) {
            return base.Channel.ListarOrdenesEstado(Estado);
        }
        
        public System.Threading.Tasks.Task<MvcApp.ProxyOrdenesCompra.OrdenesCompraBe[]> ListarOrdenesEstadoAsync(string Estado) {
            return base.Channel.ListarOrdenesEstadoAsync(Estado);
        }
    }
}
